import 'package:flutter/material.dart';
import 'package:tgs_info_app_flutter/widgets/navbar/navbar_widgets.dart';

class LoginViewModel {
  final TextEditingController _usernameController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();
  String? errorMessage;
  String? loggedInUserName;
  TextEditingController get usernameController => _usernameController;
  TextEditingController get passwordController => _passwordController;
  final List<Map<String, String>> users = [
    {
      "name": "Ahmet Yılmaz",
      "email": "ahmet.yilmaz@tgs.aero.com",
      "birthDate": "2 Nisan 1985",
      "bio": "Türk mühendis ve girişimci.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Zeynep Demir",
      "email": "zeynep.demir@tgs.aero.com",
      "birthDate": "23 Nisan 1990",
      "bio": "Ünlü Türk yazar ve akademisyen.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Mehmet Kaya",
      "email": "mehmet.kaya@tgs.aero.com",
      "birthDate": "7 Temmuz 1978",
      "bio": "Başarılı bir iş insanı ve mentor.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Elif Çelik",
      "email": "elif.celik@tgs.aero.com",
      "birthDate": "10 Ocak 1995",
      "bio": "Sanatçı ve moda tasarımcısı.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Burak Şahin",
      "email": "burak.sahin@tgs.aero.com",
      "birthDate": "5 Mayıs 1982",
      "bio": "Film yapımcısı ve yönetmen.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Merve Arslan",
      "email": "merve.arslan@tgs.aero.com",
      "birthDate": "30 Haziran 1988",
      "bio": "Başarılı bir akademisyen ve araştırmacı.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Test Kullanıcısı",
      "email": "test.info@tgs.aero.com",
      "birthDate": "30 Haziran 1988",
      "bio": "Test Kullaıcısı.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Caner Özkan",
      "email": "caner.ozkan@tgs.aero.com",
      "birthDate": "12 Şubat 1993",
      "bio": "Profesyonel sporcu ve antrenör.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Ebru Taş",
      "email": "ebru.tas@tgs.aero.com",
      "birthDate": "18 Kasım 1980",
      "bio": "Müzik sanatçısı ve besteci.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Emre Karaca",
      "email": "emre.karaca@tgs.aero.com",
      "birthDate": "25 Eylül 1986",
      "bio": "Girişimci ve teknoloji uzmanı.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Selin Güneş",
      "email": "selin.gunes@tgs.aero.com",
      "birthDate": "8 Ağustos 1992",
      "bio": "Gazeteci ve televizyon sunucusu.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Ali Çetin",
      "email": "ali.cetin@tgs.aero.com",
      "birthDate": "15 Mart 1984",
      "bio": "Yazılım geliştiricisi ve inovatör.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Fatma Yılmazer",
      "email": "fatma.yilmaz@tgs.aero.com",
      "birthDate": "20 Mayıs 1991",
      "bio": "Eğitimci ve sosyal girişimci.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Hakan Demirci",
      "email": "hakan.demirci@tgs.aero.com",
      "birthDate": "3 Ekim 1979",
      "bio": "Finans uzmanı ve danışman.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Ayşe Koca",
      "email": "ayse.koca@tgs.aero.com",
      "birthDate": "12 Aralık 1987",
      "bio": "Tasarımcı ve sanat yönetmeni.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Mustafa Erdem",
      "email": "mustafa.erdem@tgs.aero.com",
      "birthDate": "9 Şubat 1994",
      "bio": "Mühendis ve proje yöneticisi.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Gülay Şimşek",
      "email": "gulay.simsek@tgs.aero.com",
      "birthDate": "22 Temmuz 1983",
      "bio": "gulay.simsek@tgs.aero.com",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Oğuzhan Yılmaz",
      "email": "oguzan.yilmaz@tgs.aero.com",
      "birthDate": "14 Haziran 1990",
      "bio": "Pazarlama uzmanı ve lider.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Nazlı Kaya",
      "email": "nazli.kaya@tgs.aero.com",
      "birthDate": "27 Nisan 1981",
      "bio": "Mimar ve çevre aktivisti.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Serkan Aydın",
      "email": "serkan.aydin@tgs.aero.com",
      "birthDate": "11 Ağustos 1989",
      "bio": "Veri analisti ve strateji uzmanı.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Derya Öz",
      "email": "derya.oz@tgs.aero.com",
      "birthDate": "19 Ocak 1996",
      "bio": "Dijital pazarlama uzmanı.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Kerem Türker",
      "email": "kerem.turker@tgs.aero.com",
      "birthDate": "6 Mart 1985",
      "bio": "Yönetim danışmanı ve eğitmen.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Buse Yılmaz",
      "email": "buse.yilmaz@tgs.aero.com",
      "birthDate": "28 Eylül 1993",
      "bio": "Grafik tasarımcı ve illüstratör.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "İsmail Güler",
      "email": "ismail.guler@tgs.aero.com",
      "birthDate": "4 Kasım 1982",
      "bio": "Lojistik uzmanı ve girişimci.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Tolga Erkan",
      "email": "tolga.erkan@tgs.aero.com",
      "birthDate": "30 Ekim 1980",
      "bio": "Yazılım mimarı ve teknoloji lideri.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Zehra Çelik",
      "email": "zehra.celik@tgs.aero.com",
      "birthDate": "2 Şubat 1992",
      "bio": "Eğitim teknolojileri uzmanı.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Barış Yılmaz",
      "email": "baris.yilmaz@tgs.aero.com",
      "birthDate": "25 Aralık 1986",
      "bio": "Müzik prodüktörü ve DJ.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Sude Kaya",
      "email": "sude.kaya@tgs.aero.com",
      "birthDate": "13 Mart 1995",
      "bio": "Moda blog yazarı ve influencer.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Eren Şahin",
      "email": "eren.sahin@tgs.aero.com",
      "birthDate": "9 Haziran 1984",
      "bio": "Otomotiv mühendisi ve inovatör.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Aylin Demir",
      "email": "aylin.demir@tgs.aero.com",
      "birthDate": "21 Temmuz 1990",
      "bio": "Hukuk danışmanı ve avukat.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Yavuz Öztürk",
      "email": "yavuz.ozturk@tgs.aero.com",
      "birthDate": "16 Nisan 1983",
      "bio": "Girişimci ve yatırımcı.",
      "password": "password123",
      "location": "Avcılar",
    },
    {
      "name": "Esra Yılmaz",
      "email": "esra.yilmaz@tgs.aero.com",
      "birthDate": "8 Eylül 1994",
      "bio": "Diyetisyen ve sağlık koçu.",
      "password": "password123",
      "location": "Beşiktaş",
    },
    {
      "name": "Onur Kaya",
      "email": "onur.kaya@tgs.aero.com",
      "birthDate": "14 Şubat 1987",
      "bio": "Reklamcı ve yaratıcı yönetmen.",
      "password": "password123",
      "location": "Arnavutköy",
    },
    {
      "name": "Gamze Çelik",
      "email": "gamze.celik@tgs.aero.com",
      "birthDate": "3 Ağustos 1991",
      "bio": "Sosyal medya yöneticisi.",
      "password": "password123",
      "location": "Ataşehir",
    },
    {
      "name": "Umut Arslan",
      "birthDate": "26 Mayıs 1980",
      "bio": "Emlak geliştirme uzmanı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "umut.arslan@tgs.aero.com",
    },
    {
      "name": "Lale Şimşek",
      "birthDate": "19 Ekim 1993",
      "bio": "İnsan kaynakları uzmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "lale.simsek@tgs.aero.com",
    },
    {
      "name": "Kadir Yılmaz",
      "birthDate": "7 Ocak 1989",
      "bio": "Yazılım test uzmanı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "kadir.yilmaz@tgs.aero.com",
    },
    {
      "name": "İpek Kaya",
      "birthDate": "22 Mart 1985",
      "bio": "Çevre mühendisi ve aktivist.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "ipek.kaya@tgs.aero.com",
    },
    {
      "name": "Taner Demir",
      "birthDate": "15 Kasım 1992",
      "bio": "Spor koçu ve fitness uzmanı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "taner.demir@tgs.aero.com",
    },
    {
      "name": "Nihal Öz",
      "birthDate": "11 Eylül 1981",
      "bio": "Eğitim danışmanı ve yazar.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "nihal.oz@tgs.aero.com",
    },
    {
      "name": "Alper Taş",
      "birthDate": "28 Şubat 1990",
      "bio": "Oyun geliştiricisi ve tasarımcı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "alper.tas@tgs.aero.com",
    },
    {
      "name": "Berrin Yılmaz",
      "birthDate": "4 Aralık 1988",
      "bio": "Pazarlama analisti.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "berrin.yilmaz@tgs.aero.com",
    },
    {
      "name": "Cihan Kaya",
      "birthDate": "17 Temmuz 1984",
      "bio": "Finans müdürü ve strateji uzmanı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "cihan.kaya@tgs.aero.com",
    },
    {
      "name": "Ece Demir",
      "birthDate": "30 Ocak 1995",
      "bio": "Sosyal girişimci ve lider.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "ece.demir@tgs.aero.com",
    },
    {
      "name": "Ferhat Arslan",
      "birthDate": "23 Haziran 1982",
      "bio": "Mühendislik danışmanı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "ferhat.arslan@tgs.aero.com",
    },
    {
      "name": "Hande Çelik",
      "birthDate": "6 Nisan 1991",
      "bio": "Dijital içerik üreticisi.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "hande.celik@tgs.aero.com",
    },
    {
      "name": "İbrahim Yılmaz",
      "birthDate": "12 Ağustos 1980",
      "bio": "Lojistik yöneticisi.",
      "password": "password123",
      "location": "Avcılar",
      "email": "ibrahim.yilmaz@tgs.aero.com",
    },
    {
      "name": "Jale Kaya",
      "birthDate": "19 Mart 1993",
      "bio": "Eğitim teknolojisi uzmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "jale.kaya@tgs.aero.com",
    },
    {
      "name": "Kemal Demir",
      "birthDate": "25 Ekim 1986",
      "bio": "Yazılım mimarı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "kemal.demir@tgs.aero.com",
    },
    {
      "name": "Leyla Öz",
      "birthDate": "9 Şubat 1992",
      "bio": "Moda tasarımcısı ve stilist.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "leyla.oz@tgs.aero.com",
    },
    {
      "name": "Murat Şahin",
      "birthDate": "14 Mayıs 1985",
      "bio": "Girişimci ve teknoloji lideri.",
      "password": "password123",
      "location": "Avcılar",
      "email": "murat.sahin@tgs.aero.com",
    },
    {
      "name": "Nurcan Yılmaz",
      "birthDate": "20 Temmuz 1990",
      "bio": "Psikolojik danışman.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "nurcan.yilmaz@tgs.aero.com",
    },
    {
      "name": "Orhan Kaya",
      "birthDate": "3 Nisan 1983",
      "bio": "İnşaat mühendisi ve proje yöneticisi.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "orhan.kaya@tgs.aero.com",
    },
    {
      "name": "Pınar Demir",
      "birthDate": "16 Haziran 1994",
      "bio": "Diyetisyen ve beslenme uzmanı.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "pinar.demir@tgs.aero.com",
    },
    {
      "name": "Rıza Arslan",
      "birthDate": "27 Eylül 1981",
      "bio": "Finans analisti.",
      "password": "password123",
      "location": "Avcılar",
      "email": "riza.arslan@tgs.aero.com",
    },
    {
      "name": "Sinem Çelik",
      "birthDate": "8 Aralık 1989",
      "bio": "Dijital pazarlama uzmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "sinem.celik@tgs.aero.com",
    },
    {
      "name": "Tayfun Yılmaz",
      "birthDate": "22 Ocak 1995",
      "bio": "Yazılım geliştiricisi.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "tayfun.yilmaz@tgs.aero.com",
    },
    {
      "name": "Ümit Kaya",
      "birthDate": "5 Mart 1987",
      "bio": "Emlak yatırımcısı.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "umit.kaya@tgs.aero.com",
    },
    {
      "name": "Veli Demir",
      "birthDate": "18 Mayıs 1992",
      "bio": "Mühendislik danışmanı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "veli.demir@tgs.aero.com",
    },
    {
      "name": "Yasemin Öz",
      "birthDate": "11 Temmuz 1984",
      "bio": "Hukuk danışmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "yasemin.oz@tgs.aero.com",
    },
    {
      "name": "Zafer Şahin",
      "birthDate": "29 Ağustos 1990",
      "bio": "Spor yöneticisi ve koçu.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "zafer.sahin@tgs.aero.com",
    },
    {
      "name": "Aybüke Yılmaz",
      "birthDate": "13 Ekim 1986",
      "bio": "Eğitimci ve yazar.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "aybuke.yilmaz@tgs.aero.com",
    },
    {
      "name": "Burcu Kaya",
      "birthDate": "1 Şubat 1993",
      "bio": "Moda editörü.",
      "password": "password123",
      "location": "Avcılar",
      "email": "burcu.kaya@tgs.aero.com",
    },
    {
      "name": "Cemil Demir",
      "birthDate": "24 Nisan 1980",
      "bio": "Yönetim danışmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "cemil.demir@tgs.aero.com",
    },
    {
      "name": "Defne Arslan",
      "birthDate": "17 Haziran 1991",
      "bio": "Dijital içerik üreticisi.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "defne.arslan@tgs.aero.com",
    },
    {
      "name": "Engin Çelik",
      "birthDate": "30 Temmuz 1985",
      "bio": "Teknoloji girişimcisi.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "engin.celik@tgs.aero.com",
    },
    {
      "name": "Figen Yılmaz",
      "birthDate": "9 Eylül 1992",
      "bio": "Psikolog ve terapist.",
      "password": "password123",
      "location": "Avcılar",
      "email": "figen.yilmaz@tgs.aero.com",
    },
    {
      "name": "Gökhan Kaya",
      "birthDate": "22 Kasım 1988",
      "bio": "Finans uzmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "gokhan.kaya@tgs.aero.com",
    },
    {
      "name": "Hale Demir",
      "birthDate": "15 Mart 1983",
      "bio": "Eğitim teknoloji uzmanı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "hale.demir@tgs.aero.com",
    },
    {
      "name": "İlker Arslan",
      "birthDate": "28 Ocak 1994",
      "bio": "Yazılım mühendisi.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "ilker.arslan@tgs.aero.com",
    },
    {
      "name": "Jülide Çelik",
      "birthDate": "4 Mayıs 1987",
      "bio": "Moda tasarımcısı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "julide.celik@tgs.aero.com",
    },
    {
      "name": "Kaan Yılmaz",
      "birthDate": "19 Haziran 1990",
      "bio": "Girişimci ve lider.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "kaan.yilmaz@tgs.aero.com",
    },
    {
      "name": "Lütfi Kaya",
      "birthDate": "12 Ağustos 1982",
      "bio": "Lojistik uzmanı.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "lutfi.kaya@tgs.aero.com",
    },
    {
      "name": "Melis Demir",
      "birthDate": "25 Eylül 1995",
      "bio": "Dijital pazarlama uzmanı.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "melis.demir@tgs.aero.com",
    },
    {
      "name": "Necip Arslan",
      "birthDate": "8 Ekim 1981",
      "bio": "Mühendislik danışmanı.",
      "password": "password123",
      "location": "Avcılar",
      "email": "necip.arslan@tgs.aero.com",
    },
    {
      "name": "Özlem Çelik",
      "birthDate": "21 Aralık 1989",
      "bio": "Eğitim danışmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "ozlem.celik@tgs.aero.com",
    },
    {
      "name": "Ramazan Yılmaz",
      "birthDate": "3 Şubat 1993",
      "bio": "Yazılım geliştiricisi.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "ramazan.yilmaz@tgs.aero.com",
    },
    {
      "name": "Sevgi Kaya",
      "birthDate": "16 Nisan 1986",
      "bio": "Sosyal medya yöneticisi.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "sevgi.kaya@tgs.aero.com",
    },
    {
      "name": "Tahir Demir",
      "birthDate": "29 Haziran 1991",
      "bio": "Finans analisti.",
      "password": "password123",
      "location": "Avcılar",
      "email": "tahir.demir@tgs.aero.com",
    },
    {
      "name": "Ülkü Arslan",
      "birthDate": "11 Ağustos 1984",
      "bio": "Hukuk danışmanı.",
      "password": "password123",
      "location": "Beşiktaş",
      "email": "ulku.arslan@tgs.aero.com",
    },
    {
      "name": "Volkan Çelik",
      "birthDate": "24 Ekim 1990",
      "bio": "Spor koçu.",
      "password": "password123",
      "location": "Arnavutköy",
      "email": "volkan.celik@tgs.aero.com",
    },
    {
      "name": "Yıldız Yılmaz",
      "birthDate": "7 Aralık 1985",
      "bio": "Eğitimci ve yazar.",
      "password": "password123",
      "location": "Ataşehir",
      "email": "yildiz.yilmaz@tgs.aero.com",
    },
    {
      "name": "Zeki Kaya",
      "birthDate": "20 Mart 1992",
      "bio": "Teknoloji uzmanı.",
      "password": "password456",
      "location": "Avcılar",
      "email": "zeki.kaya@tgs.aero.com",
    },
  ];

  Future<void> login(BuildContext context) async {
    String username = _usernameController.text.trim().toLowerCase();
    String password = _passwordController.text.trim();
    errorMessage = null;
    Map<String, String>? currentUser;
    for (var user in users) {
      if (user["email"]?.trim().toLowerCase() == username && user["password"] == password) {
        currentUser = Map.from(user);
        break;
      }
    }
    if (currentUser != null) {
      if (currentUser["location"] == null || currentUser["location"]!.isEmpty) {
        currentUser["location"] = "Arnavutköy";
      }
      print("LoginViewModel: Giriş yapan kullanıcı: ${currentUser['email']}, Konum: ${currentUser['location']}");
      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (context) => ModernGoogleNavBar(user: currentUser!)),
      );
    } else {
      errorMessage = "Kullanıcı adı veya şifre yanlış!";
    }
  }

  void dispose() {
    _usernameController.dispose();
    _passwordController.dispose();
  }
}
